"""Tests for EngineRouter — маршрутизатор разделов."""
import pytest

from src.application.engines.base import BaseEngine, DocumentContext, SectionContent
from src.application.engines.router import EngineRouter
from src.application.engines.template_engine import TemplateEngine


class MockEngine(BaseEngine):
    """Мок-движок для тестирования маршрутизации."""

    def __init__(self, engine_name: str, handled_sections: list[str]):
        self._name = engine_name
        self._handled = set(handled_sections)

    @property
    def name(self) -> str:
        return self._name

    def can_handle(self, section_id: str) -> bool:
        return section_id in self._handled

    async def generate(self, section_id: str, section_def: dict, context: DocumentContext) -> SectionContent:
        return SectionContent(
            section_id=section_id,
            title=section_def.get("title", section_id),
            content=f"Generated by {self._name}",
            engine_name=self._name,
        )


@pytest.fixture
def sample_context():
    return DocumentContext(
        organization={"name": "Тест"},
        facility={"name": "Объект"},
        equipment=[],
        substances=[],
        persons=[],
    )


class TestEngineRouter:
    def test_find_engine_returns_first_match(self):
        engine_a = MockEngine("engine_a", ["section_1"])
        engine_b = MockEngine("engine_b", ["section_1"])
        router = EngineRouter([engine_a, engine_b])

        found = router.find_engine("section_1")
        assert found is not None
        assert found.name == "engine_a"

    def test_find_engine_returns_none_when_no_match(self):
        engine = MockEngine("engine_a", ["section_1"])
        router = EngineRouter([engine])

        assert router.find_engine("section_99") is None

    @pytest.mark.asyncio
    async def test_generate_section_uses_correct_engine(self, sample_context):
        engine_a = MockEngine("engine_a", ["title_page"])
        engine_b = MockEngine("engine_b", ["section_1"])
        router = EngineRouter([engine_a, engine_b])

        section_def = {"id": "title_page", "title": "Титульный лист"}
        result = await router.generate_section("title_page", section_def, sample_context)

        assert result.engine_name == "engine_a"
        assert "engine_a" in result.content

    @pytest.mark.asyncio
    async def test_generate_section_returns_fallback_when_no_engine(self, sample_context):
        router = EngineRouter([])

        section_def = {"id": "unknown", "title": "Unknown"}
        result = await router.generate_section("unknown", section_def, sample_context)

        assert "Движок не найден" in result.content

    def test_load_structure(self):
        router = EngineRouter([])
        structure = router.load_structure("pmla")

        assert "sections" in structure
        assert len(structure["sections"]) > 0
        assert structure["sections"][0]["id"] == "title_page"

    def test_get_engine_report(self):
        engine_a = MockEngine("engine_a", ["title_page", "toc"])
        engine_b = MockEngine("engine_b", ["section_5"])
        router = EngineRouter([engine_a, engine_b])

        report = router.get_engine_report()

        assert "title_page" in report["engine_a"]
        assert "toc" in report["engine_a"]
        assert "section_5" in report["engine_b"]
        # Some sections should be unhandled (no engine for them)
        assert len(report["unhandled"]) > 0


class TestEngineRouterIntegration:
    @pytest.mark.asyncio
    async def test_template_engine_in_router(self, sample_context):
        template_engine = TemplateEngine()
        router = EngineRouter([template_engine])

        section_def = {"id": "abbreviations", "title": "Обозначения", "template": "sections/00_abbreviations.j2"}
        result = await router.generate_section("abbreviations", section_def, sample_context)

        assert result.engine_name == "template"
        assert "АСФ" in result.content

    @pytest.mark.asyncio
    async def test_generate_all_returns_all_sections(self, sample_context):
        template_engine = TemplateEngine()
        router = EngineRouter([template_engine])

        results = await router.generate_all(sample_context)

        assert len(results) > 0
        assert "title_page" in results
        assert "abbreviations" in results
        assert "bibliography" in results
